export const grammar: { [index: string]: { person?: string, day?: string, time?: string } } = {
    // Persons
    "John": { person: "John Appleseed" },
    "Mary": { person: "Mary Shelly" },
    "Jane": { person: "Jane Austen" },
    "Albert": { person: "Albert Einstein" },
    "Coco": { person: "Coco Chanel" },
    "Rebecca": { person: "Rebecka Black" },
    "Vlad": { person: "Vlad Maraev" },
    // Weekdays
    "on Monday": { day: "Monday" },
    "on Tuesday": { day: "Tuesday" },
    "on Wednesday": { day: "Wednesday" },
    "on Thursday": { day: "Thursday" },
    "on Friday": { day: "Friday" },
    "on Saturday": { day: "Saturday" },
    "on Sunday": { day: "Sunday" },
    "Monday": { day: "Monday" },
    "Tuesday": { day: "Tuesday" },
    "Wednesday": { day: "Wednesday" },
    "Thursday": { day: "Thursday" },
    "Friday": { day: "Friday" },
    "Saturday": { day: "Saturday" },
    "Sunday": { day: "Sunday" },
    // Times
    8: { time: "8:00" },
    9: { time: "9:00" },
    10: { time: "10:00" },
    11: { time: "11:00" },
    12: { time: "12:00" },
    1: { time: "1:00" },
    2: { time: "2:00" },
    3: { time: "3:00" },
    4: { time: "4:00" },
    5: { time: "5:00" },
    "at 8 p.m.": { time: "8:00" },
    "at 9 p.m.": { time: "9:00" },
    "at 10 p.m.": { time: "10:00" },
    "at 11 p.m.": { time: "11:00" },
    "at 12 p.m.": { time: "12:00" },
    "at 1 p.m.": { time: "1:00" },
    "at 2 p.m.": { time: "2:00" },
    "at 3 p.m.": { time: "3:00" },
    "at 4 p.m.": { time: "4:00" },
    "at 5 p.m.": { time: "5:00" },
    "at 8": { time: "8:00" },
    "at 9": { time: "9:00" },
    "at 10": { time: "10:00" },
    "at 11": { time: "11:00" },
    "at 12": { time: "12:00" },
    "at 1": { time: "1:00" },
    "at 2": { time: "2:00" },
    "at 3": { time: "3:00" },
    "at 4": { time: "4:00" },
    "at 5": { time: "5:00" },
}

export const yes_no_grammar: { [index: string]: {  } } = {
    "yes": true,
    "you bet": true,
    "yeah": true,
    "no": false,
    "no way": false,
    "nope": false,
}
